### ISSUE TITLE
Can this app post link to facebook

### ISSUE THREAD

**Issue by Julian0417** [joshuainovero/Facebook-Group-Auto-Poster#1]
Hello i loved this script can update it so it can post link or both?

**Comment by joshuainovero** [comment]
Have you tried to paste the link in the entry box?

**Comment by joshuainovero** [comment]
pasting the URL into the app's entry box works perfectly, and it even displays the thumbnail of the link.

**Comment by Julian0417** [comment]
thanks it works now
